" Example Vim graphical configuration.
" Copy to ~/.gvimrc or ~/_gvimrc.

set encoding=utf-8                " Use UTF-8 everywhere.
set guioptions-=T                 " Hide toolbar.
set lines=30 columns=130          " Window dimensions.

" Or use vividchalk
colorscheme vividchalk

set guioptions-=r                 " Don't show right scrollbar

if has("mac")
  source $HOME/.vim/macgvimrc
elseif has("unix")
  source $HOME/.vim/unixgvimrc
endif
