" Example Vim graphical configuration.
" Copy to ~/.gvimrc or ~/_gvimrc.

set encoding=utf-8                " Use UTF-8 everywhere.
set guioptions-=T                 " Hide toolbar.
set guioptions-=r                 " Don't show right scrollbar

" Or use vividchalk
colorscheme molokai

" Graphical settings for MacVim
set guifont=Inconsolata:h14       " Font family and font size.
set antialias                     " MacVim: smooth fonts.

" Windo Dimensions
set fuoptions=maxvert,maxhorz     " Make fullscreen mode expand to fill screen
set lines=30 columns=130          " Window dimensions.
