" Example Vim configuration.
" Copy or symlink to ~/.vimrc or ~/_vimrc.

set nocompatible                  " Must come first because it changes other options.
filetype off

"silent! call pathogen#runtime_append_all_bundles()
call pathogen#runtime_append_all_bundles()

syntax on                         " Turn on syntax highlighting.
filetype plugin indent on         " Turn on file type detection.
set tabstop=2                     " Global tab width.
set softtabstop=2                 " Again, related
set shiftwidth=2                  " And again, related.
set expandtab                     " Use spaces instead of tabs
set smarttab
set autoindent

runtime macros/matchit.vim        " Load the matchit plugin.

set showcmd                       " Display incomplete commands.
set showmode                      " Display the mode you're in.

set backspace=indent,eol,start    " Intuitive backspacing.

set hidden                        " Handle multiple buffers better.

set wildmenu                      " Enhanced command line completion.
set wildmode=list:longest         " Complete files like a shell.

set ignorecase                    " Case-insensitive searching.
set smartcase                     " But case-sensitive if expression contains a capital letter.
set number                        " Show line numbers.
set ruler                         " Show cursor position.

set incsearch                     " Highlight matches as you type.
set hlsearch                      " Highlight matches.

set wrap                          " Turn on line wrapping.
set scrolloff=3                   " Show 3 lines of context around the cursor.

set title                         " Set the terminal's title

set visualbell                    " No beeping.

set nobackup                      " Don't make a backup before overwriting a file.
set nowritebackup                 " And again.
set directory=$HOME/.vim/tmp/,.   " Keep swap files in one location

set laststatus=2                  " Show the status line all the time
" Useful status information at bottom of screen
set statusline=[%n]\ %<%.99f\ %h%w%m%r%y\ %{fugitive#statusline()}%{exists('*CapsLockStatusline')?CapsLockStatusline():''}%=%-16(\ %l,%c-%v\ %)%P

" Tab mappings.
map <D-S-]> gt
map <D-S-[> gT
map <D-1> 1gt
map <D-2> 2gt
map <D-3> 3gt
map <D-4> 4gt
map <D-5> 5gt
map <D-6> 6gt
map <D-7> 7gt
map <D-8> 8gt
map <D-9> 9gt
map <D-0> :tablast<CR>

map tt :NERDTreeToggle<Enter>

" Settings for erlvim
let g:erlangHighlightBif=1
let g:erlangFold=1
let g:erlangFoldSplitFunction=0 " breaks regular folding
" Might need to adjust these two for OSX
let g:erlangCompletionGrep='zgrep'
let g:erlangManSuffix='erl\.gz'
let g:erlangCompletionDisplayDoc=1

" Automatic fold settings for specific files. Uncomment to use.
" autocmd FileType ruby setlocal foldmethod=syntax
" autocmd FileType css  setlocal foldmethod=indent shiftwidth=2 tabstop=2

" For the MakeGreen plugin and Ruby RSpec. Uncomment to use.
autocmd BufNewFile,BufRead *_spec.rb compiler rspec

" Shortcut to rapidly toggle `set list`
nmap <leader>l :set list!<CR>
set list "Set it on by default

" Use the same symbols as TextMate for tabstops and EOLs
set listchars=tab:▸\ ,eol:¬

" Strips trailing whitespace
function! StripTrailingWhitespace()
  normal mZ
  %s/\s\+$//e
  if line("'Z") != line(".")
    echo "Stripped whitespace\n"
  endif
  normal `Z
endfunction
autocmd FileWritePre * :call StripTrailingWhitespace()
autocmd FileAppendPre * :call StripTrailingWhitespace()
autocmd FilterWritePre * :call StripTrailingWhitespace()
autocmd BufWritePre * :call StripTrailingWhitespace()

map <F2> :call StripTrailingWhitespace()<CR>
map! <F2> :call StripTrailingWhitespace()<CR>


let g:gist_detect_filetype = 1
let g:gist_clip_command = 'pbcopy'

